package sessionstore

import (
	"context"
	"database/sql"
	"embed"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/openfloorcontrol/ofc/floor"

	_ "github.com/jackc/pgx/v5/stdlib"
)

//go:embed postgres_migrations/*.sql
var postgresMigrations embed.FS

// PostgresStore is a SessionStore backed by a Postgres database.
//
// Schema (see postgres_migrations/0001_init.sql):
//   - sessions(id, meta, next_seq, created_at)
//   - events(id, session_id, seq, room_id, private, payload_type, payload, time)
//   - event_refs(event_id, agent_id)
//
// Concurrency: per-session monotonic Seq is generated by an UPDATE on
// sessions.next_seq inside the Append transaction, which row-locks the
// session and serializes concurrent appends to the same session.
// Different sessions append in parallel.
type PostgresStore struct {
	db *sql.DB
}

// OpenPostgres connects to dsn (any pgx-compatible URL or keyword string),
// runs pending migrations, and returns a ready store. Caller is
// responsible for Close.
func OpenPostgres(ctx context.Context, dsn string) (*PostgresStore, error) {
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, fmt.Errorf("open postgres: %w", err)
	}
	if err := db.PingContext(ctx); err != nil {
		db.Close()
		return nil, fmt.Errorf("ping postgres: %w", err)
	}
	if err := migratePostgres(ctx, db); err != nil {
		db.Close()
		return nil, fmt.Errorf("migrate: %w", err)
	}
	return &PostgresStore{db: db}, nil
}

// Close releases the underlying database connection pool.
func (s *PostgresStore) Close() error { return s.db.Close() }

// --- Migrations ---

func migratePostgres(ctx context.Context, db *sql.DB) error {
	if _, err := db.ExecContext(ctx, `CREATE TABLE IF NOT EXISTS schema_migrations (
		version    INT         PRIMARY KEY,
		applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
	)`); err != nil {
		return fmt.Errorf("create schema_migrations: %w", err)
	}

	entries, err := postgresMigrations.ReadDir("postgres_migrations")
	if err != nil {
		return fmt.Errorf("read migrations dir: %w", err)
	}
	names := make([]string, 0, len(entries))
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".sql") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)

	for _, name := range names {
		version, err := parseMigrationVersion(name)
		if err != nil {
			return err
		}
		var exists bool
		if err := db.QueryRowContext(ctx, `SELECT EXISTS(SELECT 1 FROM schema_migrations WHERE version = $1)`, version).Scan(&exists); err != nil {
			return fmt.Errorf("check migration %d: %w", version, err)
		}
		if exists {
			continue
		}
		body, err := postgresMigrations.ReadFile("postgres_migrations/" + name)
		if err != nil {
			return fmt.Errorf("read migration %s: %w", name, err)
		}
		tx, err := db.BeginTx(ctx, nil)
		if err != nil {
			return fmt.Errorf("begin migration %d: %w", version, err)
		}
		if _, err := tx.ExecContext(ctx, string(body)); err != nil {
			tx.Rollback()
			return fmt.Errorf("apply migration %d (%s): %w", version, name, err)
		}
		if _, err := tx.ExecContext(ctx, `INSERT INTO schema_migrations (version) VALUES ($1)`, version); err != nil {
			tx.Rollback()
			return fmt.Errorf("record migration %d: %w", version, err)
		}
		if err := tx.Commit(); err != nil {
			return fmt.Errorf("commit migration %d: %w", version, err)
		}
	}
	return nil
}

func parseMigrationVersion(name string) (int, error) {
	// Expect "NNNN_description.sql"
	prefix := name
	if i := strings.Index(name, "_"); i > 0 {
		prefix = name[:i]
	}
	var v int
	if _, err := fmt.Sscanf(prefix, "%d", &v); err != nil {
		return 0, fmt.Errorf("migration file %q has no leading version number: %w", name, err)
	}
	return v, nil
}

// --- SessionStore impl ---

// Append inserts one event and N visibility refs in a transaction.
// Seq is allocated by incrementing sessions.next_seq, which row-locks
// the session for the duration of the tx.
func (s *PostgresStore) Append(opts floor.AppendOpts) (floor.StoredEvent, error) {
	ctx := context.Background()

	var stored floor.StoredEvent
	payload, err := json.Marshal(opts.Event)
	if err != nil {
		return stored, fmt.Errorf("marshal payload: %w", err)
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return stored, fmt.Errorf("begin: %w", err)
	}
	defer tx.Rollback()

	// Ensure the session row exists, then atomically claim a seq.
	if _, err := tx.ExecContext(ctx,
		`INSERT INTO sessions (id) VALUES ($1) ON CONFLICT (id) DO NOTHING`,
		opts.SessionID); err != nil {
		return stored, fmt.Errorf("ensure session: %w", err)
	}
	var seq int64
	if err := tx.QueryRowContext(ctx,
		`UPDATE sessions SET next_seq = next_seq + 1 WHERE id = $1 RETURNING next_seq - 1`,
		opts.SessionID).Scan(&seq); err != nil {
		return stored, fmt.Errorf("allocate seq: %w", err)
	}

	var eventID int64
	var ts struct {
		t sql.NullTime
	}
	if err := tx.QueryRowContext(ctx,
		`INSERT INTO events (session_id, seq, room_id, private, payload_type, payload, time)
		 VALUES ($1, $2, $3, $4, $5, $6, now())
		 RETURNING id, time`,
		opts.SessionID, seq, opts.RoomID, opts.Private,
		opts.Event.Type(), payload).Scan(&eventID, &ts.t); err != nil {
		return stored, fmt.Errorf("insert event: %w", err)
	}

	for _, aid := range opts.VisibleTo {
		if _, err := tx.ExecContext(ctx,
			`INSERT INTO event_refs (event_id, agent_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
			eventID, aid); err != nil {
			return stored, fmt.Errorf("insert ref: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return stored, fmt.Errorf("commit: %w", err)
	}

	stored = floor.StoredEvent{
		Seq:     uint64(seq),
		Time:    ts.t.Time,
		RoomID:  opts.RoomID,
		Event:   opts.Event,
		Private: opts.Private,
	}
	return stored, nil
}

// Read returns public (non-private) events in seq order, filtered.
func (s *PostgresStore) Read(sessionID string, filter floor.EventFilter) ([]floor.StoredEvent, error) {
	where, args := buildEventWhere(sessionID, filter)
	// Always exclude private rows from display reads.
	where = append(where, "private = false")
	query := `SELECT seq, time, room_id, private, payload_type, payload
		FROM events
		WHERE ` + strings.Join(where, " AND ") + `
		ORDER BY seq`
	return s.queryEvents(query, args)
}

// ReadForAgent returns events the agent has a visibility ref to (joins
// event_refs), in seq order. Includes private events.
func (s *PostgresStore) ReadForAgent(sessionID, agentID string, filter floor.EventFilter) ([]floor.StoredEvent, error) {
	where, args := buildEventWhere(sessionID, filter)
	args = append(args, agentID)
	agentParam := fmt.Sprintf("$%d", len(args))
	query := `SELECT e.seq, e.time, e.room_id, e.private, e.payload_type, e.payload
		FROM events e
		JOIN event_refs r ON r.event_id = e.id
		WHERE ` + strings.Join(where, " AND ") + ` AND r.agent_id = ` + agentParam + `
		ORDER BY e.seq`
	return s.queryEvents(query, args)
}

// Clear deletes events matching the filter; event_refs cascade.
func (s *PostgresStore) Clear(sessionID string, filter floor.EventFilter) error {
	where, args := buildEventWhere(sessionID, filter)
	query := `DELETE FROM events WHERE ` + strings.Join(where, " AND ")
	_, err := s.db.ExecContext(context.Background(), query, args...)
	if err != nil {
		return fmt.Errorf("clear: %w", err)
	}
	return nil
}

// SetMeta UPSERTs the meta JSONB on the session row, creating the row
// if needed.
func (s *PostgresStore) SetMeta(sessionID string, meta floor.SessionMeta) error {
	body, err := json.Marshal(meta)
	if err != nil {
		return fmt.Errorf("marshal meta: %w", err)
	}
	_, err = s.db.ExecContext(context.Background(),
		`INSERT INTO sessions (id, meta) VALUES ($1, $2)
		 ON CONFLICT (id) DO UPDATE SET meta = EXCLUDED.meta`,
		sessionID, body)
	if err != nil {
		return fmt.Errorf("set meta: %w", err)
	}
	return nil
}

// GetMeta returns the session's meta, or ErrNoSessionMeta if the row is
// missing or the meta column is NULL.
func (s *PostgresStore) GetMeta(sessionID string) (floor.SessionMeta, error) {
	var raw []byte
	err := s.db.QueryRowContext(context.Background(),
		`SELECT meta FROM sessions WHERE id = $1`, sessionID).Scan(&raw)
	if err == sql.ErrNoRows {
		return floor.SessionMeta{}, floor.ErrNoSessionMeta
	}
	if err != nil {
		return floor.SessionMeta{}, fmt.Errorf("get meta: %w", err)
	}
	if len(raw) == 0 {
		return floor.SessionMeta{}, floor.ErrNoSessionMeta
	}
	var meta floor.SessionMeta
	if err := json.Unmarshal(raw, &meta); err != nil {
		return floor.SessionMeta{}, fmt.Errorf("unmarshal meta: %w", err)
	}
	return meta, nil
}

// --- helpers ---

// buildEventWhere assembles WHERE conditions and matching $N args for
// the EventFilter. session_id is always the first arg.
func buildEventWhere(sessionID string, filter floor.EventFilter) ([]string, []any) {
	args := []any{sessionID}
	where := []string{"session_id = $1"}
	if filter.RoomID != "" {
		args = append(args, filter.RoomID)
		where = append(where, fmt.Sprintf("room_id = $%d", len(args)))
	}
	if filter.Type != "" {
		args = append(args, filter.Type)
		where = append(where, fmt.Sprintf("payload_type = $%d", len(args)))
	}
	if filter.FromSeq > 0 {
		args = append(args, filter.FromSeq)
		where = append(where, fmt.Sprintf("seq > $%d", len(args)))
	}
	return where, args
}

// queryEvents decodes rows into StoredEvent. Shared by Read and
// ReadForAgent — both project the same six columns in the same order.
func (s *PostgresStore) queryEvents(query string, args []any) ([]floor.StoredEvent, error) {
	rows, err := s.db.QueryContext(context.Background(), query, args...)
	if err != nil {
		return nil, fmt.Errorf("query events: %w", err)
	}
	defer rows.Close()

	var out []floor.StoredEvent
	for rows.Next() {
		var (
			seq         int64
			roomID      string
			private     bool
			payloadType string
			payload     []byte
			st          sql.NullTime
		)
		if err := rows.Scan(&seq, &st, &roomID, &private, &payloadType, &payload); err != nil {
			return nil, fmt.Errorf("scan event: %w", err)
		}
		ev, err := unmarshalSessionEvent(payloadType, payload)
		if err != nil {
			return nil, fmt.Errorf("decode payload type %q: %w", payloadType, err)
		}
		out = append(out, floor.StoredEvent{
			Seq:     uint64(seq),
			Time:    st.Time,
			RoomID:  roomID,
			Event:   ev,
			Private: private,
		})
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate rows: %w", err)
	}
	return out, nil
}
